---
title: "Prepare phenotypes"
author: "Ainhoa Sanchez"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(tidyverse)
library(data.table)
```

METHYLATION DATA

```{r}
library(data.table)
load("final_filtered_betas_minerva.RData")
load("pheno_minerva_filtered.RData")
betas <- data.table(t(combat_slide_array), keep.rownames = T)
iden_min <- data.table(IID = pheno$Sample_Name, paste0(pheno$Slide, "_", pheno$Array))
identical(iden_min$V2, betas$rn) # must be TRUE, confirms that samples and order are the same
betas <- iden_min[betas, on = .(V2 = rn)][, -2]
fwrite(betas, "methylation_data.csv")
```

PHENOTYPE DATA
```{r}
pheno <- readRDS("pheno_ewas_minerva.RDS")
```


```{r}
#We change the variable Smoking from categorical to numerical
pheno$smoking <- as.numeric(pheno$smoking)

# Apply the transformations so we have a binary variable
pheno$smoking[pheno$smoking %in% c(3, 99)] <- NA
pheno$smoking[pheno$smoking %in% c(10, 11, 20, 21, 22, 23, 29)] <- 1

# Convert the column to integer type
pheno$smoking <- as.integer(pheno$smoking)
```

```{r}
saveRDS(pheno, "pheno_ewas_smok_binary_minerva.RDS")
```

ANALYSIS OF THE PHENOTYPE DATA


HISTOGRAM OF THE GESTATIONAL AGE REGISTER
```{r}
hist(pheno$gest_week, col = "lightblue", main = "Histogram of gest_week register", xlab = "Gestation Weeks of the Register", ylab = "Frequency")
```
```{r}
hist_data <- hist(pheno$gest_week, plot = FALSE)

# Set counts of bins with 5 or fewer samples to zero
hist_data$counts[hist_data$counts <= 5] <- 0

# Plot the histogram with modified counts
plot(hist_data, col = "lightblue", main = "Filtered Histogram of gest_week", xlab = "Weeks of Gestation", ylab = "Frequency")
```

```{r}
#save the fixed histogram to be exported
pdf(file = "fix_gest_week_reg_hist.pdf",
    width = 12, 
    height = 8)
plot(hist_data, col = "lightblue", main = "Filtered Histogram of gest_week", xlab = "Weeks of Gestation", ylab = "Frequency")
dev.off()
```

HISTOGRAM OF THE GESTATIONAL AGE PREDICTED

```{r}
# Create a histogram of the column "DNAmAge" without plotting it
hist_data_DNAmAge <- hist(pheno$DNAmAge, plot = FALSE)

# Set counts of bins with 5 or fewer samples to zero
hist_data_DNAmAge$counts[hist_data_DNAmAge$counts <= 5] <- 0

# Plot the histogram with modified counts
plot(hist_data_DNAmAge, col = "lightblue", main = "Filtered Histogram of DNAmAge", xlab = "DNAmAge", ylab = "Frequency")
```


```{r}
hist(pheno$DNAmAge, col = "lightblue", main = "Histogram of Predicted Gestation Weeks", xlab = "Gestation Weeks Predicted", ylab = "Frequency")
```

```{r}
#save the fixed histogram to be exported
pdf(file = "fix_pred_gest_week_hist.pdf",
    width = 12, 
    height = 8)
hist(pheno$DNAmAge, col = "lightblue", main = "Histogram of Predicted Gestation Weeks", xlab = "Gestation Weeks Predicted", ylab = "Frequency")
dev.off()
```
HISTOGRAM OF SMOKING SCORE PREDICTED

```{r}
# Create a histogram of the column "smoking_pred" without plotting it
hist_data_smoking_pred <- hist(pheno$smoking_pred, plot = FALSE)

# Set counts of bins with 5 or fewer samples to zero
hist_data_smoking_pred$counts[hist_data_smoking_pred$counts <= 5] <- 0

# Plot the histogram with modified counts
plot(hist_data_smoking_pred, col = "lightcoral", main = "Filtered Histogram of smoking_pred", xlab = "smoking_pred", ylab = "Frequency")

```



```{r}
hist(pheno$smoking_pred, col = "lightcoral", main = "Histogram of Predicted Smoking Score", xlab = "Predicted Smoking Score", ylab = "Frequency")
```

```{r}
#save the fixed histogram to be exported
pdf(file = "fix_pred_smok_hist.pdf",
    width = 12, 
    height = 8)
plot(hist_data_smoking_pred, col = "lightcoral", main = "Histogram of Predicted Smoking Score", xlab = "Predicted Smoking Score", ylab = "Frequency")
dev.off()
```
CORRELATION ANALYSIS

GESTATIONAL WEEKS
```{r}
# Convert Gestational_age_register to continuous if it's not already
pheno$gest_week <- as.numeric(pheno$gest_week)

# Round Gestational_age_register to the nearest integer
pheno$gest_week <- round(pheno$gest_week)

# Remove rows with NA values
pheno <- na.omit(pheno)

# Calculate Pearson correlation
correlation <- cor(pheno$gest_week, pheno$DNAmAge)

# Print correlation
print(correlation)
```

```{r}
# Convert Gestational_age_register to continuous if it's not already
pheno$gest_week <- as.numeric(pheno$gest_week)

# Round Gestational_age_register to the nearest integer
pheno$gest_week <- round(pheno$gest_week)

# Remove rows with NA values
pheno <- na.omit(pheno)

# Create scatter plot
ggplot(pheno, aes(x = gest_week, y = DNAmAge)) +
  geom_point() +
  geom_smooth(method = "lm", col = "blue") +  # Add a linear trend line
  labs(title = "Scatter plot of Gestational Week Register vs Predicted Gestational Week",
       x = "Gestation Weeks of the Register",
       y = "Gestation Weeks Predicted") +
  theme_minimal() +
  annotate("text", x = Inf, y = -Inf, label = paste("Correlation:", round(correlation, 2)), 
           hjust = 1.1, vjust = -1.1, size = 5, color = "red", fontface = "bold")

```


```{r}
# Plot to be exported
pdf(file = "fix_corr_gest_week.pdf",
    width = 12, 
    height = 8)
ggplot(pheno_filtered, aes(x = as.factor(gest_week), y = DNAmAge)) +
  geom_boxplot(fill = "lightblue", color = "darkblue", outlier.shape = NA, notch = TRUE, width = 0.6) + 
  geom_smooth(aes(group=1), method = "lm", col = "blue") +  # Add a linear trend line
  labs(title = "Scatter plot of Gestational Week Register vs Predicted Gestational Week",
       x = "Gestation Weeks of the Register",
       y = "Gestation Weeks Predicted") +
  theme_minimal() +
  theme(
    panel.grid.major = element_blank(),   # Remove major grid lines
    panel.grid.minor = element_blank(),   # Remove minor grid lines
    plot.title = element_text(hjust = 0.5), # Center title
    axis.title.x = element_text(size = 12, face = "bold"), # Bold x-axis title
    axis.title.y = element_text(size = 12, face = "bold")  # Bold y-axis title
  ) +
  annotate("text", x = Inf, y = -Inf, label = paste("Correlation:", round(correlation, 2)), 
           hjust = 1.1, vjust = -1.1, size = 5, color = "red", fontface = "bold")
dev.off()
```







SMOKING CORRELATION

```{r}
# Calculate point-biserial correlation (special case of Pearson correlation)
correlation <- cor.test(pheno$smoking, pheno$smoking_pred)

# Print correlation coefficient
print(correlation$estimate)
```


```{r}
# Remove rows with NA values in smoking or smoking_pred
pheno <- drop_na(pheno, smoking, smoking_pred)

# Convert smoking to a factor
pheno$smoking <- factor(pheno$smoking, levels = c(0, 1), labels = c("No", "Yes"))

correlation_value <- round(correlation$estimate, 2)

# Create the boxplot
ggplot(pheno, aes(x = smoking, y = smoking_pred, fill = smoking)) +
  geom_boxplot() +
  scale_fill_manual(values = c("No" = "lightcoral", "Yes" = "lightcoral")) +
  labs(x = "Smoking in the Register", y = "Smoking Prediction Score") +
  theme_minimal() +
  theme(legend.position = "none")+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  annotate("text", x = 1.5, y = max(pheno$smoking_pred, na.rm = TRUE), 
           label = paste("Correlation:", correlation_value), color = "black", size = 5, hjust = 0.5)


```


```{r}
#Boxplot to be exported
pdf(file = "cor_no_outl_boxplot_smoking.pdf",
    width = 12, 
    height = 8)
ggplot(pheno, aes(x = smoking, y = smoking_pred, fill = smoking)) +
  geom_boxplot(outlier.shape = NA) +
  scale_fill_manual(values = c("No" = "lightcoral", "Yes" = "lightcoral")) +
  labs(x = "Smoking in the Register", y = "Smoking Prediction Score") +
  theme_minimal() +
  theme(legend.position = "none")+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  annotate("text", x = 1.5, y = max(pheno$smoking_pred, na.rm = TRUE), 
           label = paste("Correlation:", correlation_value), color = "black", size = 5, hjust = 0.5)
dev.off()
```




